### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by GawenMonnot** [ichnion/website#29]
There is not code of conduct written yet.

**Comment by dkastl** [comment]
I created it in https://github.com/ichnion/.github/blob/main/CODE_OF_CONDUCT.md
We don't need to copy it to the website. A link should be enough.

**Comment by dkastl** [comment]
This might be worth to try: https://github.com/rdilweb/docusaurus-plugin-remote-content
It coyuld be also used to prevent duplicate content of the contributing document. We could fetch both documents from https://github.com/ichnion/.github

**Comment by dkastl** [comment]
The link is suffieient so far
